services:
  - type: web
    name: portfolio-backend
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: MONGODB_URI
        fromDatabase:
          name: portfolio-db
          property: connectionString
      - key: JWT_SECRET
        generateValue: true
      - key: CLOUDINARY_CLOUD_NAME
        sync: false
      - key: CLOUDINARY_API_KEY
        sync: false
      - key: CLOUDINARY_API_SECRET
        sync: false
      - key: CORS_ORIGIN
        value: https://portfolio-pi-peach-84.vercel.app
      - key: API_BASE_URL
        value: https://portfolio-j9s6.onrender.com
      - key: DB_RETRY_DELAY_MS
        value: 5000
      - key: DB_MAX_RETRIES
        value: 10

databases:
  - name: portfolio-db
    plan: free
    databaseName: portfolio
    user: portfolio_user
